esphome:
  name: hall-9
  friendly_name: Hall 9 Room 1
 
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "990limTqrMH+hZO2Eg6kvbDyueKOd0y5IBtEpieOnCY="

ota:
  - platform: esphome
    password: "example"

wifi:
  ssid: "example"
  password: "12345678"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hall-9"
    password: "12345678"

captive_portal:

####
packages:
  voice_assistant:
    url: https://github.com/chriopter/hall-9
    ref: main
    file: packages/voice_assistant.yaml
    refresh: 0d
  radar_sensor:
    url: https://github.com/chriopter/hall-9
    ref: main
    file: packages/radar_sensor.yaml
    refresh: 0d
  temperature_sensor:
    url: https://github.com/chriopter/hall-9
    ref: main
    file: packages/temperature_sensor.yaml
    refresh: 0d
  esp32_config:
    url: https://github.com/chriopter/hall-9
    ref: main
    file: packages/esp32_config.yaml
    refresh: 0d
  esphome_updater:
    url: https://github.com/chriopter/hall-9
    ref: main
    file: packages/esphome_updater.yaml
    refresh: 0d
