esphome:
  name: hall-9
  friendly_name: Hall 9 Room 1
 
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "990limTqrMH+hZO2Eg6kvbDyueKOd0y5IBtEpieOnCY="

ota:
  - platform: esphome
    password: "example"

wifi:
  ssid: "example"
  password: "12345678"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hall-9"
    password: "12345678"

captive_portal:

####
external_components:
  - source: github://chriopter/hall-9@main
    refresh: 0d
    # Either include all packages maintained here for complete hardware featureset or limit like this by umcommenting:
    # components: [voice_assistant, radar_sensor, temperature_sensor, esp32_config, esphome_updater]
