button:
  - platform: restart
    name: "ESP32 Restart"
    id: but_rest
  
sensor:
  - platform: internal_temperature
    name: "ESP32 Internal Temperature"
  - platform: wifi_signal
    name: "ESP32 WiFi Signal Strength"
    update_interval: 60s
  - platform: uptime
    name: "ESP32  Uptime"
    update_interval: 60s
    unit_of_measurement: "s" # You can set this to "minutes" or "hours" as needed

esphome:
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    - light.turn_on:
        id: led_ww
        blue: 100%
        brightness: 60%
        effect: fast pulse
    - speaker.volume_set: 1.0

psram:
  mode: octal  # quad for N8R2 and octal for N16R8
  speed: 80MHz

api:
  on_client_connected:
    then:
      - delay: 50ms
      - light.turn_off: led_ww
      - micro_wake_word.start:
  on_client_disconnected:
    then:
      - voice_assistant.stop: 
