substitutions:
  device_version: "0.0.0"  # This will be overridden by CI

esphome:
  project:
    name: "chriopter.hall-9"
    version: "${device_version}"  # Use the substitution

text_sensor:
  - platform: version
    name: "Hall 9 ESPHome Version"
    id: esphome_version
