esphome:
  project:
    name: "chriopter.hall-9"
    version: "1.0.5"  # Use the substitution

text_sensor:
  - platform: text
    name: "Hall 9 Project Version"
    id: project_version
    update_interval: never
    initial_value: "${project_version}"
