esphome:
  project:
    name: "chriopter.hall-9"
    version: "1.0.0"  # Current version of your project

sensor:
  - platform: template
    name: "Hall 9 Version Check"
    id: check_version
    update_interval: 24h

text_sensor:
  - platform: template
    name: "Hall 9 Firmware Status"
    id: firmware_status
    icon: "mdi:update"
  - platform: version
    name: "Hall 9 ESPHome Version"
    id: esphome_version

binary_sensor:
  - platform: template
    name: "Hall 9 Update Available"
    id: update_available
    device_class: update
