substitutions:
  device_version: "1.0.4"  # This will be overridden by CI

esphome:
  project:
    name: "chriopter.hall-9"
    version: "1.0.4"  # Use the substitution

text_sensor:
  - platform: version
    name: "Hall 9 ESPHome Version"
    id: esphome_version
