# LD2410 Radar
uart:
  id: uart2410
  tx_pin: GPIO20
  rx_pin: GPIO21
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: uart2410
  throttle: 1000ms

binary_sensor:
  - platform: ld2410
    has_target:
      name: "${friendly_name} Presence"
    has_moving_target:
      name: "${friendly_name} Moving Target"
    has_still_target:
      name: "${friendly_name} Still Target"

sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name: Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance


number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    
text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"
