name: CI
permissions:
  contents: write
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .esphome
            .pio
            ~/.platformio
            ~/.platformio/packages
            ~/.platformio/penv
            ~/.platformio/platforms
            ~/.platformio/toolchains
          key: ${{ runner.os }}-pio-${{ hashFiles('*.yaml', '.esphome/**/*.h', '.esphome/**/*.cpp') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Get version for releases
        id: get_version
        if: github.event_name == 'release'
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build ESPHome firmware
        id: build
        uses: esphome/build-action@main
        with:
          yaml-file: hall-9.yaml
          version: ${{ github.event_name == 'release' && steps.get_version.outputs.version || '' }}
